title: Onchain Writing Hackathon 
description: An open-source framework for organizing and running onchain writing hackathons.
theme: jekyll-theme-slate
author: Adrienne Shulman
url: "https://atenger.github.io/onchain-writing-hackathon-framework/"
